name: Build STL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openscad/openscad
    steps:
      - uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir ./dist

      - name: Build teardrop.scad
        run: openscad ./src/models/assemblies/teardrop/teardrop.scad -o ./dist/teardrop.stl

      - name: Build squaredrop.scad
        run: openscad ./src/models/assemblies/squaredrop/squaredrop.scad -o ./dist/squaredrop.stl

      - name: Build preview image
        run: xvfb-run -a openscad ./src/models/assemblies/teardrop.scad -o ./dist/preview.png --imgsize 2650,1440

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/teardrop.stl
            ./dist/squaredrop.stl
            ./dist/preview.png
