name: Build STL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create dist directory
        run: mkdir ./dist

      - name: Build STLs
        run: task build

      - name: Build Preview Images
        run: task preview -- -P Showcase

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/teardrop.stl
            ./dist/squaredrop.stl
            ./dist/teardrop.png
            ./dist/squaredrop.png
