name: Build STL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openscad/openscad
    steps:
      - uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir ./dist

      - name: Build STL
        run: openscad ./src/models/teardrop.scad -o ./dist/teardrop.stl
