name: Build STL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openscad/openscad
    steps:
      - uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir ./dist

      - name: Build teardrop.scad
        run: openscad ./src/models/assemblies/teardrop.scad -o ./dist/teardrop.stl

      - name: Build shell.scad
        run: openscad ./src/models/assemblies/shell.scad -o ./dist/shell.stl

      - name: Build preview image
        run: xvfb-run -a openscad ./src/models/assemblies/teardrop.scad -o ./dist/preview.png

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/teardrop.stl
            ./dist/shell.stl
            ./dist/preview.png

