name: Build STL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openscad/openscad
    steps:
      - uses: actions/checkout@v3

      - name: install just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Create dist directory
        run: mkdir ./dist

      - name: Build
        run: just

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/teardrop.stl
            ./dist/squaredrop.stl
            ./dist/teardrop.png
            ./dist/squaredrop.png
