name: Build STL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openscad/openscad
    steps:
      - uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir ./dist

      - name: Build STL
        run: openscad ./src/models/teardrop.scad -o ./dist/teardrop.stl

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/teardrop.stl

